# Prod Override Values for my Helm Chart

container:
  image: nginx:1.27-alpine

<<<<<<< HEAD
replicaCount: 6
=======
replicaCount: 3
>>>>>>> 1f74ca801fa4e9edb88cfa5ca3580d025dbc91e4

service:
  type: NodePort
  port: 80 # Default service port
  targetPort: 80 # Default target port for the container
  nodePort: 30080 # Default NodePort value

